spring:
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

  messages:
    basename: classpath:messages_pt_BR
    encoding: UTF-8

server:
  error:
    include-message: always
    include-stacktrace: never
    include-exception: false
    whitelabel:
      enabled: true
  port: ${APP_PORT}
  servlet:
    context-path: "/api/v1/payment"
