spring:
  datasource:
    hikari:
      connectionTimeout: ${HIRAKI_TIMEOUT}
      maximumPoolSize: ${HIRAKI_MAX_POLLSIZE}
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  
  #drop n create table again, good for testing, comment this in production
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  messages:
    basename: classpath:messages_pt_BR
    encoding: UTF-8

server:
  error:
    include-message: always
    include-stacktrace: never
    include-exception: false
    whitelabel:
      enabled: true