spring:
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  
  #drop n create table again, good for testing, comment this in production
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  messages:
    basename: classpath:messages_pt_BR
    encoding: UTF-8

  flyway:
    url: ${POSTGRES_URL}
    user: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    baseline-on-migrate: true

server:
  error:
    include-message: always
    include-stacktrace: never
    include-exception: false
    whitelabel:
      enabled: true
  port: ${APP_PORT}
  servlet:
    context-path: "/api/v1/payment"